- name: Patch non HA Linux Servers
  hosts: all
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest

  - name: Check for reboot hint.
    shell: LAST_KERNEL=$(rpm -q --last kernel | awk 'NR==1{sub(/kernel-/,""); print $1}'); CURRENT_KERNEL=$(uname -r); if [ $LAST_KERNEL != $CURRENT_KERNEL ]; then echo 'reboot'; else echo 'no'; fi
    ignore_errors: true
    register: reboot_hint

  - name: reboot
    shell: ( sleep 3 && /sbin/reboot & )
    async: 0
    poll: 0 
    when: reboot_hint.stdout.find("reboot") != -1
    register: reboot
  
  - name: Wait for the server to come back
    wait_for_connection:
      delay: 15
      timeout: 300
